---
name: Lint and Build

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Lint and build
    runs-on: docker
    steps:
      - name: ⤵️ Checkout Configuration
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: 🏗 Install dependencies
        run: npm ci

      - name: 🎈 Run lint
        run: npm run lint

      - name: 🚀 Run dist
        run: npm run dist

      - name: ✨ Upload artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        if: github.event_name != 'pull_request'
        with:
          path: |
            global-mod.js

  update-nightly:
    name: Update Nightly tags
    runs-on: docker
    if: github.event_name != 'pull_request'
    needs: build
    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v4

      - name: 🚀 Update nightly tag
        run: |
          git tag -fa "nightly" -m "Nightly release"
          git push -f origin --tags
        env:
          GIT_COMMITTER_NAME: Actions Bot
          GIT_COMMITTER_EMAIL: actions@1d.lol

  release:
    name: Publish Nightly Release
    runs-on: docker
    if: github.event_name != 'pull_request'
    needs:
      - build
      - update-nightly
    steps:
      - name: 💾 Download artifact
        uses: https://code.forgejo.org/forgejo/download-artifact@v4

      - name: 🚀 Create nightly release
        uses: akkuman/gitea-release-action@v1
        with:
          name: Nightly
          tag_name: nightly
          prerelease: true
          target_commitish: ${{ github.SHA }}
          files: |
            $DIRECTORY/global-mod.js
        env:
          DIRECTORY: ${{ github.workspace }}/global-mod/artifact
