---
name: Lint and Build

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
    paths-ignore:
      - "assets/**"
      - "*.md"
      - ".editorconfig"
      - ".giattributes"
      - ".gitignore"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Checkout Configuration
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: 'package-lock.json'

      - name: 🏗 Install dependencies
        run: npm install

      - name: 🎈 Run lint
        run: npm run lint

      - name: 🚀 Run dist
        run: npm run dist

      - name: ✨ Upload artifact
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        if: github.event_name != 'pull_request'
        with:
          path: |
            global-mod.js

  update-nightly:
    name: Update Nightly tags
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build
    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: 🚀 Update nightly tag
        run: |
          git tag -fa "nightly" -m "Nightly release"
          git push -f origin --tags
        env:
          GIT_COMMITTER_NAME: Actions Bot
          GIT_COMMITTER_EMAIL: actions@1d.lol

  release:
    name: Publish Nightly Release
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs:
      - build
      - update-nightly
    steps:
      - name: 💾 Download artifact
        uses: https://code.forgejo.org/forgejo/download-artifact@d8d0a99033603453ad2255e58720b460a0555e1e # v4

      - name: 🚀 Create nightly release
        uses: akkuman/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1
        with:
          name: Nightly
          tag_name: nightly
          prerelease: true
          target_commitish: ${{ github.SHA }}
          files: |
            artifact/global-mod.js
