---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - name: ⤵️ Checkout Configuration
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: 21

      - name: 🏗 Install dependencies
        run: npm ci

      - name: 🚀 Run dist
        run: npm run dist

      - name: ✨ Archive production artifacts
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          path: |
            global-mod.js

  release:
    runs-on: docker
    steps:
      - name: ⤵️ Checkout Configuration
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: ✨ Retrieve build artifacts
        uses: https://code.forgejo.org/forgejo/download-artifact@d8d0a99033603453ad2255e58720b460a0555e1e # v4

      - name: 🎯 Get version
        shell: bash
        run: |
          VERSION_TAG=$(jq -r .version package.json)
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: 🧾 Generate release notes
        shell: bash
        # yamllint disable rule:line-length
        run: |
          PREVIOUS=$(git describe --tags --abbrev=0)
          CURRENT=$(git rev-parse HEAD)
          (git log "$PREVIOUS^..$CURRENT" --format="- %h - %s (%an, %ar)" | sed '/Merge/d') > CHANGELOG.md
        # yamllint enable rule:line-length

      - name: 📦 Move artifact to root
        run: mv artifact/global-mod.js global-mod.js

      - name: 🗳 Pack GitHub Release
        shell: bash
        run: |
          tar -cvzf global-mod-github.tar.gz \
              images/ \
              src/ \
              global-mod.js \
              hacs.json \
              LICENSE.md \
              package-lock.json \
              package.json \
              README.md

      - name: 🚀 Create release
        uses: akkuman/gitea-release-action@f119011bd6c95ab53d2084ace7b539694ce9b252 # v1
        with:
          name: "v${{ env.VERSION_TAG }}"
          tag_name: "v${{ env.VERSION_TAG }}"
          body_path: CHANGELOG.md
          files: |
            global-mod.js
            global-mod-github.tar.gz

  increment-version:
    runs-on: docker
    steps:
      - name: ⤵️ Checkout Configuration
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
        with:
          node-version: 21

      - name: ⏫ Increment patch version
        run: |
          npm version patch -m "Bump to v%s"
          git push -f origin
        env:
          GIT_COMMITTER_NAME: Actions Bot
          GIT_COMMITTER_EMAIL: actions@1d.lol
