---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Checkout Configuration
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: 'package-lock.json'

      - name: 🏗 Install dependencies
        run: npm install

      - name: 🚀 Run dist
        run: npm run dist

      - name: ✨ Archive production artifacts
        uses: https://code.forgejo.org/forgejo/upload-artifact@16871d9e8cfcf27ff31822cac382bbb5450f1e1e # v4
        with:
          path: |
            global-mod.js

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: ⤵️ Checkout Configuration
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: ✨ Retrieve build artifacts
        uses: https://code.forgejo.org/forgejo/download-artifact@d8d0a99033603453ad2255e58720b460a0555e1e # v4

      - name: 🎯 Get version
        shell: bash
        run: |
          VERSION_TAG=$(jq -r .version package.json)
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: 🧾 Generate release notes
        shell: bash
        # yamllint disable rule:line-length
        run: |
          PREVIOUS=$(git describe --tags --abbrev=0)
          CURRENT=$(git rev-parse HEAD)
          (git log "$PREVIOUS^..$CURRENT" --format="- %h - %s (%an, %ar)" | sed '/Merge/d') > CHANGELOG.md
        # yamllint enable rule:line-length

      - name: 📦 Move artifact to root
        run: mv artifact/global-mod.js global-mod.js

      - name: 🚀 Create release
        uses: akkuman/gitea-release-action@fe8e0322804b48e34e3bddbbf6335bd2b1046eb7 # v1
        with:
          name: "v${{ env.VERSION_TAG }}"
          tag_name: "v${{ env.VERSION_TAG }}"
          body_path: CHANGELOG.md
          files: |
            global-mod.js

  increment-version:
    runs-on: ubuntu-latest
    needs: [increment-version]
    steps:
      - name: ⤵️ Checkout Configuration
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: 🏗 Setup Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: 'package-lock.json'

      - name: ⏫ Increment patch version
        run: |
          npm version patch -m "Bump to v%s"
          git push -f origin
        env:
          GIT_COMMITTER_NAME: Actions Bot
          GIT_COMMITTER_EMAIL: actions@1d.lol
